# Generated by Django 4.0.5 on 2022-07-20 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=30)),
                ('diseno', models.IntegerField()),
                ('calidad', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('numeroRollo', models.IntegerField()),
                ('cantidadYarda', models.FloatField()),
                ('estante', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('diseno', models.IntegerField()),
                ('calidad', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('numeroRollo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadYarda', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('diseno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disenoTela', to='app_inventario.tela')),
                ('estante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventario.estante')),
                ('tela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombreTela', to='app_inventario.tela')),
            ],
        ),
    ]
