# Generated by Django 4.0.5 on 2022-07-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='diseno',
            field=models.IntegerField(),
        ),
    ]
