# Generated by Django 2.2 on 2022-06-08 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tela',
            name='cantidadRollo',
        ),
        migrations.AddField(
            model_name='inventario',
            name='cantidadYarda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantYarda', to='app_inventario.Tela'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colorTela', to='app_inventario.Tela'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='numeroRollo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numRollo', to='app_inventario.Tela'),
        ),
        migrations.AddField(
            model_name='tela',
            name='tipoTela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inventario.Tipo_Tela'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='tela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombreTela', to='app_inventario.Tela'),
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidadYarda', models.IntegerField()),
                ('estanteDestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estanteDestino', to='app_inventario.Estante')),
                ('estanteOrigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estanteOrigen', to='app_inventario.Estante')),
                ('telaProduc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventario.Tela')),
            ],
        ),
    ]
