# Generated by Django 2.2 on 2022-06-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0002_auto_20220608_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tela',
            name='cantidadYarda',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidadYarda',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
