# Generated by Django 2.2 on 2022-06-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0003_auto_20220610_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='color',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='numeroRollo',
        ),
    ]
