# Generated by Django 2.2 on 2022-06-15 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0004_auto_20220613_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidadYarda',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='DetalleSalida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidadYarda', models.FloatField()),
                ('calidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calidadTela', to='app_inventario.Tela')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colorTela', to='app_inventario.Tela')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomTela', to='app_inventario.Tela')),
                ('numeroRollo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeroRolloTela', to='app_inventario.Tela')),
            ],
        ),
    ]
