# Generated by Django 2.2 on 2022-06-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0005_auto_20220615_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesalida',
            name='calidad',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='detallesalida',
            name='color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='detallesalida',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='detallesalida',
            name='numeroRollo',
            field=models.IntegerField(),
        ),
    ]
