# Generated by Django 2.2 on 2022-06-20 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0006_auto_20220616_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesalida',
            name='estante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_inventario.Estante'),
            preserve_default=False,
        ),
    ]
