# Generated by Django 2.2 on 2022-06-20 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0007_detallesalida_estante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribuidora',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='tipo_tela',
            name='distribuidora',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Distribuidora',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
